// Display-only catalog bundled for an instant first visit.
// Live /api/menu data replaces this snapshot before ordering is enabled.
const MENU_SNAPSHOT = [
  {
    "id": "fr-chicken-roll",
    "cat": "fried",
    "name": "Chicken Roll",
    "unit": "1 Piece",
    "minQty": 10,
    "step": 5,
    "seasonal": false,
    "img": "images/fr-chicken-roll.png",
    "price": 20,
    "stock": null,
    "available": true
  },
  {
    "id": "fr-cutlet-beef",
    "cat": "fried",
    "name": "Cutlet (Beef)",
    "unit": "1 Piece",
    "minQty": 10,
    "step": 5,
    "seasonal": false,
    "img": "images/fr-cutlet-beef.png",
    "price": 20,
    "stock": null,
    "available": true
  },
  {
    "id": "fr-cutlet-chicken",
    "cat": "fried",
    "name": "Cutlet (Chicken)",
    "unit": "1 Piece",
    "minQty": 10,
    "step": 5,
    "seasonal": false,
    "img": "images/fr-cutlet-chicken.png",
    "price": 18,
    "stock": null,
    "available": true
  },
  {
    "id": "fr-fried-momos",
    "cat": "fried",
    "name": "Fried Momos",
    "unit": "1 Piece",
    "minQty": 10,
    "step": 5,
    "seasonal": false,
    "img": "fr-fried-momos.png",
    "price": 25,
    "stock": null,
    "available": true
  },
  {
    "id": "fr-irachi-pathiri",
    "cat": "fried",
    "name": "Irachi Pathiri",
    "unit": "1 Piece",
    "minQty": 10,
    "step": 5,
    "seasonal": false,
    "img": "fr-irachi-pathiri.png",
    "price": 20,
    "stock": null,
    "available": true
  },
  {
    "id": "fr-kallumakaya",
    "cat": "fried",
    "name": "Kallumakaya",
    "unit": "1 Piece",
    "minQty": 10,
    "step": 5,
    "seasonal": false,
    "img": "images/fr-kallumakaya.png",
    "price": 22,
    "stock": null,
    "available": true
  },
  {
    "id": "fr-kunafa-chicken",
    "cat": "fried",
    "name": "Kunafa Chicken",
    "unit": "1 Piece",
    "minQty": 10,
    "step": 5,
    "seasonal": false,
    "img": "fr-kunafa-chicken.png",
    "price": 40,
    "stock": null,
    "available": true
  },
  {
    "id": "fr-samoosa-beef",
    "cat": "fried",
    "name": "Samoosa (Beef)",
    "unit": "1 Piece",
    "minQty": 10,
    "step": 5,
    "seasonal": false,
    "img": "images/fr-samoosa-beef.png",
    "price": 18,
    "stock": null,
    "available": true
  },
  {
    "id": "fr-samoosa-chicken",
    "cat": "fried",
    "name": "Samoosa (Chicken)",
    "unit": "1 Piece",
    "minQty": 10,
    "step": 5,
    "seasonal": false,
    "img": "images/fr-samoosa-chicken.png",
    "price": 15,
    "stock": null,
    "available": true
  },
  {
    "id": "fr-steamed-momos",
    "cat": "fried",
    "name": "Steamed Momos",
    "unit": "1 Piece",
    "minQty": 10,
    "step": 5,
    "seasonal": false,
    "img": "fr-steamed-momos.png",
    "price": 25,
    "stock": null,
    "available": true
  },
  {
    "id": "fr-unnakaya",
    "cat": "fried",
    "name": "Unnakaya",
    "unit": "1 Piece",
    "minQty": 10,
    "step": 5,
    "seasonal": false,
    "img": "images/fr-unnakaya.png",
    "price": 15,
    "stock": null,
    "available": true
  },
  {
    "id": "fz-chicken-roll",
    "cat": "frozen",
    "name": "Chicken Roll",
    "unit": "1 Piece",
    "minQty": 10,
    "step": 5,
    "seasonal": false,
    "img": "images/fz-chicken-roll.png",
    "price": 17.5,
    "stock": null,
    "available": true
  },
  {
    "id": "fz-cutlet-beef",
    "cat": "frozen",
    "name": "Cutlet (Beef)",
    "unit": "1 Piece",
    "minQty": 10,
    "step": 5,
    "seasonal": false,
    "img": "images/fz-cutlet-beef.png",
    "price": 23,
    "stock": null,
    "available": true
  },
  {
    "id": "fz-cutlet-chicken",
    "cat": "frozen",
    "name": "Cutlet (Chicken)",
    "unit": "1 Piece",
    "minQty": 10,
    "step": 5,
    "seasonal": false,
    "img": "images/fz-cutlet-chicken.png",
    "price": 20,
    "stock": null,
    "available": true
  },
  {
    "id": "fz-kallumakaya-masala",
    "cat": "frozen",
    "name": "Kallumakaya (w/ masala)",
    "unit": "1 Piece",
    "minQty": 10,
    "step": 5,
    "seasonal": false,
    "img": "images/fz-kallumakaya-masala.png",
    "price": 20,
    "stock": null,
    "available": true
  },
  {
    "id": "fz-kallumakaya-plain",
    "cat": "frozen",
    "name": "Kallumakaya (w/o masala)",
    "unit": "1 Piece",
    "minQty": 10,
    "step": 5,
    "seasonal": false,
    "img": "images/fz-kallumakaya-plain.png",
    "price": 18,
    "stock": null,
    "available": true
  },
  {
    "id": "fz-kunafa-chicken",
    "cat": "frozen",
    "name": "Kunafa Chicken",
    "unit": "1 Piece",
    "minQty": 10,
    "step": 5,
    "seasonal": false,
    "img": "fz-kunafa-chicken.png",
    "price": 35,
    "stock": null,
    "available": true
  },
  {
    "id": "fz-momos-chicken",
    "cat": "frozen",
    "name": "Momos Chicken",
    "unit": "1 Piece",
    "minQty": 10,
    "step": 5,
    "seasonal": false,
    "img": "fz-momos-chicken.png",
    "price": 20,
    "stock": null,
    "available": true
  },
  {
    "id": "fz-samoosa-beef",
    "cat": "frozen",
    "name": "Samoosa (Beef)",
    "unit": "1 Piece",
    "minQty": 10,
    "step": 5,
    "seasonal": false,
    "img": "images/fz-samoosa-beef.png",
    "price": 15,
    "stock": null,
    "available": true
  },
  {
    "id": "fz-samoosa-chicken",
    "cat": "frozen",
    "name": "Samoosa (Chicken)",
    "unit": "1 Piece",
    "minQty": 10,
    "step": 5,
    "seasonal": false,
    "img": "images/fz-samoosa-chicken.png",
    "price": 15,
    "stock": null,
    "available": true
  },
  {
    "id": "fz-unnakaya",
    "cat": "frozen",
    "name": "Unnakaya",
    "unit": "1 Piece",
    "minQty": 10,
    "step": 5,
    "seasonal": false,
    "img": "images/fz-unnakaya.png",
    "price": 12,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-batura",
    "cat": "mains",
    "name": "Batura",
    "unit": "1 Piece",
    "minQty": 10,
    "step": 5,
    "seasonal": false,
    "img": "mc-batura.png",
    "price": 15,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-beef-biriyani",
    "cat": "mains",
    "name": "Beef Biriyani",
    "unit": "1 KG",
    "minQty": 1,
    "step": 0.5,
    "seasonal": false,
    "img": "images/mc-beef-biriyani.png",
    "price": 800,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-beef-curry-coconut",
    "cat": "mains",
    "name": "Beef Curry (Coconut)",
    "unit": "1 KG",
    "minQty": 1,
    "step": 0.5,
    "seasonal": false,
    "img": "mc-beef-curry-coconut.png",
    "price": 800,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-beef-curry-masala",
    "cat": "mains",
    "name": "Beef Curry (Masala)",
    "unit": "1 KG",
    "minQty": 1,
    "step": 0.5,
    "seasonal": false,
    "img": "mc-beef-curry-masala.png",
    "price": 750,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-beef-dry-fry",
    "cat": "mains",
    "name": "Beef Dry Fry",
    "unit": "1 KG",
    "minQty": 1,
    "step": 0.5,
    "seasonal": false,
    "img": "mc-beef-dry-fry.png",
    "price": 800,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-beef-stew",
    "cat": "mains",
    "name": "Beef Stew",
    "unit": "1 KG",
    "minQty": 1,
    "step": 0.5,
    "seasonal": false,
    "img": "mc-beef-stew.png",
    "price": 850,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-butter-chicken",
    "cat": "mains",
    "name": "Butter Chicken",
    "unit": "1 KG",
    "minQty": 1,
    "step": 0.5,
    "seasonal": false,
    "img": "images/mc-butter-chicken.png",
    "price": 650,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-chicken-65",
    "cat": "mains",
    "name": "Chicken 65",
    "unit": "1 KG",
    "minQty": 1,
    "step": 0.5,
    "seasonal": false,
    "img": "images/mc-chicken-65.png",
    "price": 650,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-chicken-biriyani",
    "cat": "mains",
    "name": "Chicken Biriyani",
    "unit": "1 KG",
    "minQty": 1,
    "step": 0.5,
    "seasonal": false,
    "img": "images/mc-chicken-biriyani.png",
    "price": 750,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-chicken-curry",
    "cat": "mains",
    "name": "Chicken Curry",
    "unit": "1 KG",
    "minQty": 1,
    "step": 0.5,
    "seasonal": false,
    "img": "images/mc-chicken-curry.png",
    "price": 350,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-chicken-fry",
    "cat": "mains",
    "name": "Chicken Fry",
    "unit": "1 KG",
    "minQty": 1,
    "step": 0.5,
    "seasonal": false,
    "img": "images/mc-chicken-fry.png",
    "price": 500,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-chicken-stew",
    "cat": "mains",
    "name": "Chicken Stew",
    "unit": "1 KG",
    "minQty": 1,
    "step": 0.5,
    "seasonal": false,
    "img": "images/mc-chicken-stew.png",
    "price": 550,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-chilly-chicken",
    "cat": "mains",
    "name": "Chilly Chicken",
    "unit": "1 KG",
    "minQty": 1,
    "step": 0.5,
    "seasonal": false,
    "img": "images/mc-chilly-chicken.png",
    "price": 500,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-fish-biriyani",
    "cat": "mains",
    "name": "Fish Biriyani",
    "unit": "1 KG",
    "minQty": 1,
    "step": 0.5,
    "seasonal": true,
    "img": "images/mc-fish-biriyani.png",
    "price": 1100,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-fish-chilly",
    "cat": "mains",
    "name": "Fish Chilly",
    "unit": "1 KG",
    "minQty": 1,
    "step": 0.5,
    "seasonal": true,
    "img": "mc-fish-chilly.png",
    "price": 750,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-fish-moly",
    "cat": "mains",
    "name": "Fish Moly",
    "unit": "1 KG",
    "minQty": 1,
    "step": 0.5,
    "seasonal": true,
    "img": "mc-fish-moly.png",
    "price": 650,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-fish-mulakuttath",
    "cat": "mains",
    "name": "Fish Mulakuttath",
    "unit": "1 KG",
    "minQty": 1,
    "step": 0.5,
    "seasonal": true,
    "img": "mc-fish-mulakuttath.png",
    "price": 400,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-garlic-chicken",
    "cat": "mains",
    "name": "Garlic Chicken",
    "unit": "1 KG",
    "minQty": 1,
    "step": 0.5,
    "seasonal": false,
    "img": "images/mc-garlic-chicken.png",
    "price": 450,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-ginger-chicken",
    "cat": "mains",
    "name": "Ginger Chicken",
    "unit": "1 KG",
    "minQty": 1,
    "step": 0.5,
    "seasonal": false,
    "img": "images/mc-ginger-chicken.png",
    "price": 450,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-hummus",
    "cat": "mains",
    "name": "Hummus",
    "unit": "1 KG",
    "minQty": 1,
    "step": 0.5,
    "seasonal": false,
    "img": "images/mc-hummus.png",
    "price": 350,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-kallumakaya-fry",
    "cat": "mains",
    "name": "Kallumakaya Fry",
    "unit": "1 KG",
    "minQty": 1,
    "step": 0.5,
    "seasonal": false,
    "img": "mc-kallumakaya-fry.png",
    "price": 650,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-kallumakaya-masala",
    "cat": "mains",
    "name": "Kallumakaya Masala",
    "unit": "1 KG",
    "minQty": 1,
    "step": 0.5,
    "seasonal": false,
    "img": "mc-kallumakaya-masala.png",
    "price": 700,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-kannuvecha-pathiri-fried",
    "cat": "mains",
    "name": "Kannuvecha Pathiri (Fried)",
    "unit": "1 Piece",
    "minQty": 20,
    "step": 5,
    "seasonal": false,
    "img": "mc-kannuvecha-pathiri-fried.png",
    "price": 15,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-kannuvecha-pathiri-half-cooked",
    "cat": "mains",
    "name": "Kannuvecha Pathiri (Half cooked)",
    "unit": "1 Piece",
    "minQty": 20,
    "step": 5,
    "seasonal": false,
    "img": "mc-kannuvecha-pathiri-half-cooked.png",
    "price": 13,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-kozhi-nirachath-broiler",
    "cat": "mains",
    "name": "Kozhi Nirachath (Broiler)",
    "unit": "1 KG",
    "minQty": 1,
    "step": 0.5,
    "seasonal": false,
    "img": "mc-kozhi-nirachath-broiler.png",
    "price": 500,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-kozhi-nirachath-spring",
    "cat": "mains",
    "name": "Kozhi Nirachath (Spring)",
    "unit": "1 KG",
    "minQty": 1,
    "step": 0.5,
    "seasonal": false,
    "img": "mc-kozhi-nirachath-spring.png",
    "price": 350,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-kuboos",
    "cat": "mains",
    "name": "Kuboos",
    "unit": "1 Piece",
    "minQty": 10,
    "step": 5,
    "seasonal": false,
    "img": "mc-kuboos.png",
    "price": 10,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-madhooth",
    "cat": "mains",
    "name": "Madhooth",
    "unit": "1 KG",
    "minQty": 1,
    "step": 0.5,
    "seasonal": false,
    "img": "images/mc-madhooth.png",
    "price": 700,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-mutton-biriyani",
    "cat": "mains",
    "name": "Mutton Biriyani",
    "unit": "1 KG",
    "minQty": 1,
    "step": 0.5,
    "seasonal": true,
    "img": "images/mc-mutton-biriyani.png",
    "price": 1250,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-mutton-masala",
    "cat": "mains",
    "name": "Mutton Masala",
    "unit": "1 KG",
    "minQty": 1,
    "step": 0.5,
    "seasonal": true,
    "img": "mc-mutton-masala.png",
    "price": 1100,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-mutton-stew",
    "cat": "mains",
    "name": "Mutton Stew",
    "unit": "1 KG",
    "minQty": 1,
    "step": 0.5,
    "seasonal": true,
    "img": "mc-mutton-stew.png",
    "price": 1250,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-mutton-varattiyath",
    "cat": "mains",
    "name": "Mutton Varattiyath",
    "unit": "1 KG",
    "minQty": 1,
    "step": 0.5,
    "seasonal": true,
    "img": "mc-mutton-varattiyath.png",
    "price": 1150,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-neypathal",
    "cat": "mains",
    "name": "Neypathal",
    "unit": "1 Piece",
    "minQty": 10,
    "step": 5,
    "seasonal": false,
    "img": "mc-neypathal.png",
    "price": 20,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-paal-kappa",
    "cat": "mains",
    "name": "Paal Kappa",
    "unit": "1 KG",
    "minQty": 1,
    "step": 0.5,
    "seasonal": false,
    "img": "mc-paal-kappa.png",
    "price": 300,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-pasta",
    "cat": "mains",
    "name": "Pasta",
    "unit": "1 KG",
    "minQty": 1,
    "step": 0.5,
    "seasonal": false,
    "img": "mc-pasta.png",
    "price": 750,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-pepper-chicken",
    "cat": "mains",
    "name": "Pepper Chicken",
    "unit": "1 KG",
    "minQty": 1,
    "step": 0.5,
    "seasonal": false,
    "img": "images/mc-pepper-chicken.png",
    "price": 400,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-thai-chicken",
    "cat": "mains",
    "name": "Thai Chicken",
    "unit": "1 KG",
    "minQty": 1,
    "step": 0.5,
    "seasonal": false,
    "img": "images/mc-thai-chicken.png",
    "price": 700,
    "stock": null,
    "available": true
  },
  {
    "id": "mc-turkish-chicken",
    "cat": "mains",
    "name": "Turkish Chicken",
    "unit": "1 KG",
    "minQty": 1,
    "step": 0.5,
    "seasonal": false,
    "img": "images/mc-turkish-chicken.png",
    "price": 700,
    "stock": null,
    "available": true
  }
];

export default MENU_SNAPSHOT;
