-- Run before deploying this release: node migrate.js menu_offers.sql
-- Re-runnable. Existing prices, menu IDs and historical invoices are preserved.
-- This baseline creates schema, not the original menu catalog. For local test
-- recovery use restore-test-menu.js or clone a populated Neon branch first.
CREATE TABLE IF NOT EXISTS categories (
  id text PRIMARY KEY
);
-- Older populated databases require a category name. Preserve their labels;
-- the minimal baseline used by earlier local installs has only an id column.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_attribute
    WHERE attrelid = 'categories'::regclass AND attname = 'name' AND NOT attisdropped
  ) THEN
    INSERT INTO categories(id, name) VALUES
      ('fried', 'Fried Snacks'), ('frozen', 'Frozen Snacks'), ('mains', 'Biriyani & Curries')
    ON CONFLICT (id) DO NOTHING;
  ELSE
    INSERT INTO categories(id) VALUES ('fried'), ('frozen'), ('mains')
    ON CONFLICT (id) DO NOTHING;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS menu_items (
  id text PRIMARY KEY,
  category_id text NOT NULL REFERENCES categories(id),
  name text NOT NULL,
  unit text NOT NULL DEFAULT '',
  min_qty numeric NOT NULL DEFAULT 1,
  step_qty numeric NOT NULL DEFAULT 1,
  seasonal boolean NOT NULL DEFAULT false,
  image text NOT NULL DEFAULT '',
  default_price numeric NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS inventory (
  menu_item_id text PRIMARY KEY REFERENCES menu_items(id),
  selling_price numeric NOT NULL,
  stock numeric,
  available boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS customers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  phone text NOT NULL,
  email text,
  address text,
  latitude numeric,
  longitude numeric
);

CREATE TABLE IF NOT EXISTS orders (
  id text PRIMARY KEY,
  customer_id bigint NOT NULL REFERENCES customers(id),
  invoice_id text NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  order_mode text NOT NULL,
  notes text,
  total numeric NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  payment_status text NOT NULL DEFAULT 'unpaid',
  paymet text NOT NULL DEFAULT 'cod',
  archived boolean NOT NULL DEFAULT false,
  delivery_date date,
  delivery_slot text,
  stock_reserved boolean NOT NULL DEFAULT false,
  invoice_share_token text NOT NULL DEFAULT replace(gen_random_uuid()::text, '-', ''),
  synced_at timestamptz
);

CREATE TABLE IF NOT EXISTS order_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id text NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  menu_item_id text NOT NULL REFERENCES menu_items(id),
  quantity numeric NOT NULL,
  unit_price numeric NOT NULL,
  subtotal numeric NOT NULL
);

CREATE TABLE IF NOT EXISTS sales_summary (
  summary_date date PRIMARY KEY,
  orders_count integer NOT NULL DEFAULT 0,
  revenue numeric NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS app_migrations (name text PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS retired boolean NOT NULL DEFAULT false;
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS is_combo boolean NOT NULL DEFAULT false;
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS stock_group_id text REFERENCES menu_items(id);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM app_migrations WHERE name = 'menu-offers-v1') THEN
    UPDATE inventory i SET stock = COALESCE(i.stock, 0) + r.qty
    FROM (SELECT oi.menu_item_id, SUM(oi.quantity) qty FROM order_items oi
      JOIN orders o ON o.id = oi.order_id WHERE o.stock_reserved
      GROUP BY oi.menu_item_id) r WHERE i.menu_item_id = r.menu_item_id;
    UPDATE orders SET stock_reserved = false WHERE stock_reserved;
    UPDATE inventory i SET stock = FLOOR(i.stock) FROM menu_items m
      WHERE m.id = i.menu_item_id AND m.category_id IN ('fried', 'frozen');
    INSERT INTO app_migrations(name) VALUES ('menu-offers-v1');
  END IF;
END $$;

WITH additions(id, category_id, name, unit, min_qty, step_qty, price, combo) AS (VALUES
  ('mc-broasted-chicken', 'mains', 'Broasted Chicken', 'Full chicken - 8 pieces', 1, 1, 600, false),
  ('mc-ghee-rice', 'mains', 'Ghee Rice', '1 KG', 1, 0.5, 600, false),
  ('mc-butter-garlic-chicken', 'mains', 'Butter Garlic Chicken', '1 KG', 1, 0.5, 725, false),
  ('mc-patthiri', 'mains', 'Patthiri', '1 Piece', 25, 5, 7, false),
  ('mc-chapatis', 'mains', 'Chapatis', '1 Piece', 15, 5, 8, false),
  ('mc-chattipathiri-1kg', 'mains', 'Chattipathiri - 1 kg', '1 pack (1 kg)', 1, 1, 350, false),
  ('mc-chattipathiri-1-5kg', 'mains', 'Chattipathiri - 1.5 kg', '1 pack (1.5 kg)', 1, 1, 475, false),
  ('mc-chattipathiri-2kg', 'mains', 'Chattipathiri - 2 kg', '1 pack (2 kg)', 1, 1, 650, false),
  ('mc-vegetable-stew', 'mains', 'Vegetable Stew - Coconut Milk', '1 KG', 1, 0.5, 250, false),
  ('fz-irachi-pathiri', 'frozen', 'Irachi Pathiri', '1 Piece', 10, 5, 15, false),
  ('combo-broasted', 'mains', 'Broasted full chicken + Hummus 250 g + Kuboos 11 pieces', '1 combo', 1, 1, 850, true),
  ('combo-neypathal', 'mains', 'Neypathal 11 pieces + Beef Masala 375 g', '1 combo', 1, 1, 650, true),
  ('combo-batura', 'mains', 'Batura 11 pieces + Butter Chicken 500 g', '1 combo', 1, 1, 600, true)
)
INSERT INTO menu_items(id, category_id, name, unit, min_qty, step_qty, default_price, seasonal, image, is_combo)
SELECT a.id, a.category_id, a.name, a.unit, a.min_qty, a.step_qty, a.price, false, '', a.combo
FROM additions a WHERE NOT EXISTS (SELECT 1 FROM menu_items m WHERE m.id = a.id
  OR (m.category_id = a.category_id AND lower(m.name) = lower(a.name)))
ON CONFLICT DO NOTHING;

INSERT INTO inventory(menu_item_id, selling_price, stock, available)
SELECT m.id, m.default_price, 0, true FROM menu_items m
WHERE NOT EXISTS (SELECT 1 FROM inventory i WHERE i.menu_item_id = m.id);

-- Retain the row for historical order/invoice references.
UPDATE menu_items SET retired = true WHERE category_id = 'frozen'
  AND (id = 'fz-kallumakaya-plain' OR lower(name) IN ('plain kallumakaya', 'kallumakaya (w/o masala)'));

-- Link newly imported variants on EVERY run. Existing owners/manual counts
-- remain authoritative; only a completely new family gets a MAX opening count.
DO $$
DECLARE family record;
BEGIN
  FOR family IN
    WITH snacks AS (
      SELECT m.id, m.stock_group_id, i.stock, CASE
        WHEN lower(name) LIKE '%momo%' THEN 'momos'
        WHEN lower(name) LIKE '%kallumakaya%' THEN 'kallumakaya'
        ELSE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') END AS family_name
      FROM menu_items m JOIN inventory i ON i.menu_item_id=m.id
      WHERE category_id IN ('fried', 'frozen') AND NOT retired
    ) SELECT array_agg(id) ids, COALESCE(MIN(stock_group_id), MIN(id)) owner,
        COUNT(DISTINCT stock_group_id) owner_count, FLOOR(MAX(COALESCE(stock, 0))) opening_stock
      FROM snacks GROUP BY family_name
  LOOP
    IF family.owner_count > 1 THEN
      RAISE EXCEPTION 'Conflicting shared stock owners for %. Review counts before merging.', family.ids;
    END IF;
    IF family.owner_count = 0 THEN
      UPDATE inventory SET stock=family.opening_stock WHERE menu_item_id=family.owner;
    END IF;
    UPDATE menu_items SET stock_group_id=family.owner
      WHERE id=ANY(family.ids) AND stock_group_id IS NULL;
  END LOOP;
  INSERT INTO app_migrations(name) VALUES ('shared-snack-stock-v1') ON CONFLICT DO NOTHING;
END $$;

CREATE TABLE IF NOT EXISTS offers (
  slug text PRIMARY KEY,
  title text NOT NULL CHECK (length(title) BETWEEN 1 AND 100),
  items jsonb NOT NULL CHECK (jsonb_typeof(items) = 'array'),
  starts_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL DEFAULT (now() + interval '24 hours'),
  closed boolean NOT NULL DEFAULT false,
  CHECK (expires_at > starts_at)
);
CREATE INDEX IF NOT EXISTS idx_offers_expiry ON offers(expires_at);

-- Apply safeguards to both fresh databases and the earlier incomplete bootstrap.
-- Preserve existing invoice tokens; fill only missing ones. Invalid historical
-- data causes an atomic rollback instead of silently deleting/correcting rows.
ALTER TABLE orders ALTER COLUMN invoice_share_token SET DEFAULT replace(gen_random_uuid()::text, '-', '');
UPDATE orders SET invoice_share_token=replace(gen_random_uuid()::text, '-', '') WHERE invoice_share_token IS NULL;
ALTER TABLE orders ALTER COLUMN invoice_share_token SET NOT NULL;
ALTER TABLE orders ALTER COLUMN invoice_id SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS orders_invoice_id_key ON orders(invoice_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_orders_invoice_share_token ON orders(invoice_share_token);
DO $$
DECLARE guard record;
BEGIN
  FOR guard IN SELECT * FROM (VALUES
    ('inventory', 'inventory_stock_nonnegative', 'stock IS NULL OR stock >= 0'),
    ('inventory', 'inventory_price_nonnegative', 'selling_price IS NOT NULL AND selling_price >= 0'),
    ('orders', 'orders_status_allowed', 'status IS NOT NULL AND status IN (''pending'',''accepted'',''declined'',''completed'')'),
    ('orders', 'orders_payment_status_allowed', 'payment_status IS NOT NULL AND payment_status IN (''paid'',''unpaid'')'),
    ('orders', 'orders_total_nonnegative', 'total IS NOT NULL AND total >= 0'),
    ('menu_items', 'menu_items_quantities_positive', 'min_qty > 0 AND step_qty > 0'),
    ('menu_items', 'menu_items_price_nonnegative', 'default_price >= 0'),
    ('order_items', 'order_items_values_valid', 'quantity > 0 AND unit_price >= 0 AND subtotal >= 0')
  ) AS guards(table_name, constraint_name, predicate)
  LOOP
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid=guard.table_name::regclass AND conname=guard.constraint_name) THEN
      EXECUTE format('ALTER TABLE %I ADD CONSTRAINT %I CHECK (%s) NOT VALID', guard.table_name, guard.constraint_name, guard.predicate);
    END IF;
    EXECUTE format('ALTER TABLE %I VALIDATE CONSTRAINT %I', guard.table_name, guard.constraint_name);
  END LOOP;
END $$;
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_payment_status ON orders(payment_status);
CREATE INDEX IF NOT EXISTS idx_orders_customer_id ON orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_menu_item_id ON order_items(menu_item_id);
CREATE INDEX IF NOT EXISTS idx_menu_items_category ON menu_items(category_id);
